# Generated by Django 6.0.3 on 2026-08-15 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('users', '0002_user_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(default='', editable=False, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='ticket_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='unique_project_key_per_workspace'),
        ),
    ]
