# Generated by Django 6.0.3 on 2026-07-20 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.BigIntegerField(unique=True)),
                ('repository_name', models.CharField(max_length=300)),
                ('repository_full_name', models.CharField(max_length=300)),
                ('default_branch', models.CharField(max_length=100)),
                ('webhook_id', models.BigIntegerField(blank=True, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_integrations', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_integration', to='projects.project')),
            ],
            options={
                'db_table': 'github_integrations',
            },
        ),
        migrations.DeleteModel(
            name='GitRepository',
        ),
    ]
