# Generated by Django 6.0.3 on 2026-08-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
