# Generated by Django 6.0.3 on 2026-08-21 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_project_key_project_ticket_sequence_and_more'),
        ('tickets', '0004_remove_ticket_estimated_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('MEMBER_ADDED', 'Member Added'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_ROLE_CHANGED', 'Member Role Changed'), ('EPIC_CREATED', 'Epic Created'), ('EPIC_DELETED', 'Epic Deleted'), ('GITHUB_CONNECTED', 'GitHub Connected'), ('GITHUB_DISCONNECTED', 'GitHub Disconnected'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('TICKET_UNASSIGNED', 'Ticket Unassigned'), ('TICKET_STATUS_CHANGED', 'Ticket Status Changed'), ('TICKET_COLUMN_CHANGED', 'Ticket Column Changed'), ('TICKET_PRIORITY_CHANGED', 'Ticket Priority Changed'), ('TICKET_DUE_DATE_CHANGED', 'Ticket Due Date Changed'), ('TICKET_EPIC_CHANGED', 'Ticket Epic Changed'), ('TICKET_STORY_POINTS_CHANGED', 'Story Points Changed'), ('TICKET_COMMENTED', 'Ticket Commented'), ('TICKET_GITHUB_PUSH', 'GitHub Push Linked'), ('TICKET_GITHUB_PR_OPENED', 'GitHub PR Opened'), ('TICKET_GITHUB_PR_MERGED', 'GitHub PR Merged')], db_index=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='activity_ac_project_0d9dc1_idx'), models.Index(fields=['ticket', '-created_at'], name='activity_ac_ticket__c33f3a_idx'), models.Index(fields=['project', 'verb', '-created_at'], name='activity_ac_project_e9e00d_idx')],
            },
        ),
    ]
