# Generated by Django 6.0.3 on 2026-08-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='verb',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('MEMBER_ADDED', 'Member Added'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_ROLE_CHANGED', 'Member Role Changed'), ('EPIC_CREATED', 'Epic Created'), ('EPIC_DELETED', 'Epic Deleted'), ('GITHUB_CONNECTED', 'GitHub Connected'), ('GITHUB_DISCONNECTED', 'GitHub Disconnected'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('TICKET_UNASSIGNED', 'Ticket Unassigned'), ('TICKET_STATUS_CHANGED', 'Ticket Status Changed'), ('TICKET_COLUMN_CHANGED', 'Ticket Column Changed'), ('TICKET_GITHUB_PUSH', 'GitHub Push Linked'), ('TICKET_GITHUB_PR_OPENED', 'GitHub PR Opened'), ('TICKET_GITHUB_PR_MERGED', 'GitHub PR Merged')], db_index=True, max_length=40),
        ),
    ]
