# Generated by Django 6.0.3 on 2026-08-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='estimated_hours',
        ),
    ]
